# Generated by Django 4.1.4 on 2022-12-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=50)),
                ("rated", models.CharField(max_length=50)),
                ("released", models.DateField()),
                ("runtime", models.DurationField()),
                ("genre", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                ("writer", models.CharField(max_length=200)),
                ("actors", models.CharField(max_length=200)),
                ("plot", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("awards", models.CharField(max_length=100)),
                ("poster", models.URLField()),
                ("metascore", models.CharField(max_length=50)),
                ("imdb_rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("imdb_votes", models.PositiveIntegerField()),
                ("imdb_id", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("total_seasons", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=50)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="movierecommenderapp.show",
                    ),
                ),
            ],
        ),
    ]
